#!/usr/bin/env bash

set -e # exit on error
set -v # be verbose.

# use this as the boot strap script
# Assumes that salt is already installed, and that there script is trusted.
# It pulls the latest code from master and runs that.

# every thing is assumed to be running as root.
rm -rf /opt/magudi && mkdir -p /opt/magudi
rm -rf /opt/pillar && mkdir -p /opt/pillar

# download provisioning code.
git clone git@github.com:pythonindia/magudi /opt/magudi

# $PILLAR_GIT_URL should be available in the environment. (may be? /etc/environment)
git clone git@github.com:pythonindia/pillar /opt/pillar

# if salt is not installed, uncomment the following line.
# wget -O - https://bootstrap.saltstack.com | sh

# run salt-call/provision.
mkdir -p /srv
ln -sf /opt/magudi/salt/roots /srv/salt
ln -sf /opt/pillar /srv/pillar

if [ "$1" = "--debug" ]; then
  LOG_LEVEL="debug"
else
  LOG_LEVEL="warning"  # The default
fi

salt-call --local state.highstate -l $LOG_LEVEL

# Ensure that next run will have the updated version
# of the this file. Self updating!!!
cp /opt/magudi/provision /usr/bin/provision

cd # go back to the home directory.
